name: tarpass
channels:
  - conda-forge
dependencies:
  - python=3.11
  - scipy
  - scikit-learn
  - pandas
  - matplotlib
  - seaborn
  - rdkit
  - openbabel
  - biopython
  - meeko
  - pip
  - pip:
      - more_itertools
      - pyyaml
      - tqdm
      - statsmodels
      - scikit-posthocs
      - plip
      - fcd