[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tarpass"
version = "0.1.0"
dependencies = [
    # "requests>=2.25.1",
]

[tool.setuptools.packages.find]
where = ["."]

[tool.setuptools]
package-dir = {"" = "./"}